### ISSUE TITLE
OpenSSL support?

### ISSUE THREAD

**Issue by AyeYessir** [cfenoy/influxdb-slurm-monitoring#2]
Our InfluxDB server requires information be sent with OpenSSL. Would it be possible to enable or add this feature to the plugin? Or is this something that needs to be requested through SchedMD since they support the package now? Thanks!

**Comment by AyeYessir** [comment]
Could be as easy as adding: "curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0);"

**Comment by cfenoy** [comment]
Hi @AdamCarlson84 , this would need to be requested to SchedMD as they are the ones supporting this plugin now, and I'm not sure if this repo is up to date with the version shipped with Slurm. As the change is relatively simple you can just send them the patch.
What is exactly failing for you? Are you using self-signed certificates for your InfluxDB server?

**Comment by AyeYessir** [comment]
Hey! Yep, the code is different now. I found it and already made a pull request for them through there. Yes, it is a self signed cert. If I recall correctly, every attempt to send data was resulting in a TLS negotiation failure; so the data was getting to the host and then being rejected.

**Comment by cfenoy** [comment]
@AdamCarlson84 , I'm not sure if disabling the SSL verification by hardcoding it into the code is the right approach. Couldn't you get a properly signed certificate or add your CA to your Influx clients? (Let's encrypt may be a good option)

**Comment by AyeYessir** [comment]
Hmmmm, well my exact error is "TLS handshake error from <IP:PORT>: remote error: tls: unknown certificate".... we are working on getting away from self signed certs, but aren't there yet. And I need stats! Perhaps an option to disable in the config is better than just a blanket check?
