### ISSUE TITLE
How To Install Plugin

### ISSUE THREAD

**Issue by ifelsefi** [cfenoy/influxdb-slurm-monitoring#3]
Hello

Could you share some steps on how to compile, install, configure this plugin?

**Comment by cfenoy** [comment]
Hi @ifelsefi ,
This plugin is already included in Slurm since version 18.08, so if you have a recent enough version of slurm it should already be in your installation. If you're building the RPMs yourself, you may need to install libcurl-devel before compiling slurm to get the plugin installed.
